### ISSUE TITLE
Cannot access with generated ID/PW

### ISSUE THREAD

**Issue by kination** [Theodo-UK/nestjs-admin#234] opened 2021-05-23 08:08 UTC
Hello,
I've just setup the configs, and add ID/PW for admin via `nestjs-admin createAdminUser`.
But I'm keep failing to access

<img width="646" alt="Screen Shot 2021-05-23 at 17 05 49" src="https://user-images.githubusercontent.com/1720209/119252839-4daeaf80-bbe9-11eb-9c95-e32114cbeb2c.png">

(I've didn't setup any other entities`DefaultAdminSite` except 'AdminUser'...can this cause problem?)

**Comment by LeoAnesi** [comment] 2021-12-19 08:17
Hi @djKooks,

I feel like this is a duplicate of : https://github.com/Theodo-UK/nestjs-admin/issues/219 do you confirm ?

**Closed** 2023-05-05 04:43 UTC
